// Aggregate receipt dedupe rows (Task 21): the ONLY thing the ControlPlane
// keeps about a submission besides the anonymous totals. A receiptId is a
// random id generated by the room — it carries no reverse mapping to
// room/player/game and no such columns may ever be added here.
//
// Retention: the dedupe window is 24h ("same receiptId twice within 24h
// counts once; a >24h-old receipt is refused and never recounted"). Rows
// are kept 7 days — comfortably past the dedupe window, since the outbox's
// own retry window is 5 minutes — then expired lazily on each submit.
export const RECEIPT_DEDUPE_MS = 24 * 60 * 60 * 1000;
export const RECEIPT_RETENTION_MS = 7 * 24 * 60 * 60 * 1000;

export const findReceipt = (sql: SqlStorage, receiptId: string): number | null =>
  sql
    .exec<{ received_at_ms: number }>(
      "SELECT received_at_ms FROM aggregate_receipts WHERE receipt_id = ?",
      receiptId,
    )
    .toArray()[0]?.received_at_ms ?? null;

export const insertReceipt = (sql: SqlStorage, receiptId: string, nowMs: number): void => {
  sql.exec(
    "INSERT INTO aggregate_receipts (receipt_id, received_at_ms) VALUES (?, ?)",
    receiptId,
    nowMs,
  );
};

// Lazy expiry — runs AFTER the dedupe check so a stale receipt still
// refuses its resend on the way out (a receipt is deleted only once it is
// far too old to ever be resent legitimately).
export const expireReceipts = (sql: SqlStorage, nowMs: number): number =>
  sql.exec("DELETE FROM aggregate_receipts WHERE received_at_ms < ?", nowMs - RECEIPT_RETENTION_MS)
    .rowsWritten;
